version: "2"
services:
  randomtime:
    build: .
    ports:
      - 8090:3000
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres
    ports:
      - "5433:5432"
    env_file:
      - .env